title: Västerås Azure User Group
description: Your Azure meetup in the town of cucumbers! 🥒
title_image: "https://vazug.cloud/media/vazug.jpg"
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman